// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUoGTOt8S12F9KE4DjRUepU2W28gmv5To',
    appId: '1:286945614620:web:a5f482ea420ef1f8c0f8d9',
    messagingSenderId: '286945614620',
    projectId: 'blmapp-931a0',
    authDomain: 'blmapp-931a0.firebaseapp.com',
    storageBucket: 'blmapp-931a0.firebasestorage.app',
    measurementId: 'G-W8CKL3VQVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChY-oczR5YzPudVF-RdkV8GyzAVTQBqis',
    appId: '1:286945614620:android:ee2a0ff541069035c0f8d9',
    messagingSenderId: '286945614620',
    projectId: 'blmapp-931a0',
    storageBucket: 'blmapp-931a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtagfGjb-YG0rRzUrS3gWCvbDWHDJLxYI',
    appId: '1:286945614620:ios:7be8cfd0eac0faf0c0f8d9',
    messagingSenderId: '286945614620',
    projectId: 'blmapp-931a0',
    storageBucket: 'blmapp-931a0.firebasestorage.app',
    iosClientId: '286945614620-td4vd44qj7qvl0t4467ev072i79676cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtagfGjb-YG0rRzUrS3gWCvbDWHDJLxYI',
    appId: '1:286945614620:ios:7be8cfd0eac0faf0c0f8d9',
    messagingSenderId: '286945614620',
    projectId: 'blmapp-931a0',
    storageBucket: 'blmapp-931a0.firebasestorage.app',
    iosClientId: '286945614620-td4vd44qj7qvl0t4467ev072i79676cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUoGTOt8S12F9KE4DjRUepU2W28gmv5To',
    appId: '1:286945614620:web:595858ad43b1d9e2c0f8d9',
    messagingSenderId: '286945614620',
    projectId: 'blmapp-931a0',
    authDomain: 'blmapp-931a0.firebaseapp.com',
    storageBucket: 'blmapp-931a0.firebasestorage.app',
    measurementId: 'G-ZW238QTVKH',
  );
}
